---
title: "关于小学生跑步的案例"
author: "王敏杰"
date: "`r Sys.Date()`"
output: 
  officedown::rdocx_document:
    number_sections: yes
    df_print: kable
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo     = FALSE,
    warning  = FALSE, 
    message  = FALSE,
    fig.asp  = 0.618,
    dpi      = 300
)
options(digits = 3)
```


我们的课程目标：用R语言生成一份完整的word分析报告，内容包括读取数据，画出图形以及建立模型。



```{r libraries, echo = FALSE}
library(tidyverse)
library(cmdstanr)
check_cmdstan_toolchain(fix = TRUE, quiet = TRUE)
options(mc.cores = parallel::detectCores())
theme_set(bayesplot::theme_default(base_size = 14))
```


# 数据

```{r}
d <- haven::read_sav("./data/Study 4.sav")

d
```

# stan

```{r, results='hide'}
stan_program <- write_stan_file("
data{
  int<lower=0> N;
  vector[N] Selfish;
  vector[N] ZEI;
  vector[N] Embarrass;
  array[N] int<lower=0, upper=1>  Accident;
}

parameters{
  vector[4] a;
  real b;
  vector[4] c;
  real<lower=0> sigma;
}

transformed parameters{
  vector[N] mu;
  vector[N] theta;
  for(i in 1:N) {
      mu[i] = a[1] + a[2] * Selfish[i] + a[3] * ZEI[i] + a[4] * Selfish[i] * ZEI[i];
   theta[i] = c[1] + c[2] * Selfish[i] + c[3] * ZEI[i] + c[4] * Selfish[i] * ZEI[i] + b * Embarrass[i];
  }
}

model{
  for(i in 1:N) {
    Embarrass[i] ~ normal(mu[i], sigma);
     Accident[i] ~ bernoulli_logit(theta[i]);
  }
}

generated quantities {
  real IndexOfModMed;
  real aSSLow;
  real aSSHigh;
  real abLow;
  real abHigh;

  // Index of Moderated Mediation
  IndexOfModMed = a[4] * b;

  // Simple Slopes
  aSSLow  = a[2] + a[4] * (-1);  
  aSSHigh = a[2] + a[4] * (1) ;   
   
  // Conditional Indirect Effects
  abLow  = aSSLow * b;
  abHigh = aSSHigh* b;

}
                                                                
")

stan_data <- list(
  N         = nrow(d),
  Selfish   = d$Selfish,
  ZEI       = d$ZEI,
  Embarrass = d$Embarrass,
  Accident  = d$Accident
)

mod_stan <- cmdstan_model(stan_file = stan_program)

fit_stan <- mod_stan$sample(data = stan_data)
```



```{r}
fit_stan$summary(c("a[2]", "a[3]", "a[4]", "c[2]", "c[3]", "c[4]", "b",
                   "IndexOfModMed", "aSSLow", "aSSHigh", "abLow", "abHigh")) %>% 
  flextable::flextable() %>% 
  flextable::autofit()
```


# brms
```{r}
library(brms)

mod <- brm(
    bf(Embarrass ~ Selfish + ZEI + Selfish:ZEI,             family = gaussian()) +
    bf(Accident  ~ Selfish + ZEI + Selfish:ZEI + Embarrass, family = bernoulli(link = "logit")) +
    set_rescor(FALSE),
  data   = d,
  chains = 4,
  cores  = 4
)
```



```{r}
print(mod, digits = 3)

fixef(mod)
```


```{r}
draws <- as_draws_df(mod)

tbl_orders <- c("a1", "a2", "a3", 
                "c1", "c2", "c3",
                "b",
                "IndexOfModMed", "abLow", "abHigh")

draws %>% 
  transmute(
    a1     = `b_Embarrass_Selfish`,
    a2     = `b_Embarrass_ZEI`,
    a3     = `b_Embarrass_Selfish:ZEI`,
    c1     = `b_Accident_Selfish`,
    c2     = `b_Accident_ZEI`,
    c3     = `b_Accident_Selfish:ZEI`,
    b      = `b_Accident_Embarrass` 
  ) %>% 
  mutate(
    IndexOfModMed     = a3 * b,
    abLow             = (a1 + a3 * (-1)) * b,
    abHigh            = (a1 + a3 * ( 1)) * b
  ) %>% 
  pivot_longer(
    cols          = everything(),
    names_to      = "item",
    values_to     = "value"
  ) %>% 
  group_by(item) %>% 
  ggdist::mean_hdi(.width = .95) %>% 
  arrange(factor(item, levels = tbl_orders)) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 3) %>% 
  flextable::line_spacing(space = 0.7) %>% 
  flextable::color(j = "value", color = "red") %>% 
  flextable::autofit()
```


# brms using non-linear syntax

```{r}
library(brms)

mod <- brm(
    bf(Embarrass ~ Intercept + a1*Selfish + a2*ZEI + a3*Selfish*ZEI,  
       Intercept ~ 1,
       a1 ~ 1,
       a2 ~ 1,
       a3 ~ 1,
       nl = TRUE,
       family = gaussian(link = "identity")
      ) +
    bf(Accident ~ Intercept + c1*Selfish + c2*ZEI + c3*Selfish*ZEI + b*Embarrass, 
       Intercept ~ 1,
       c1 ~ 1,
       c2 ~ 1,
       c3 ~ 1,
       b  ~ 1,
       nl = TRUE,
       family = bernoulli(link = "logit")
    ) +
    set_rescor(FALSE),
    data   = d,
    iter = 2000, warmup = 1000, chains = 4, cores = 4
)
```



```{r}
print(mod, digits = 3)

fixef(mod)
```


```{r}
draws <- as_draws_df(mod)

tbl_orders <- c("a1", "a2", "a3", 
                "c1", "c2", "c3",
                "b",
                "IndexOfModMed", "abLow", "abHigh")

draws %>% 
  transmute(
    a1     = b_Embarrass_a1_Intercept,
    a2     = b_Embarrass_a2_Intercept,
    a3     = b_Embarrass_a3_Intercept,
    c1     = b_Accident_c1_Intercept,
    c2     = b_Accident_c2_Intercept,
    c3     = b_Accident_c3_Intercept,
    b      = b_Accident_b_Intercept 
  ) %>% 
  mutate(
    IndexOfModMed     = a3 * b,
    abLow             = (a1 + a3 * (-1)) * b,
    abHigh            = (a1 + a3 * ( 1)) * b
  ) %>% 
  pivot_longer(
    cols          = everything(),
    names_to      = "item",
    values_to     = "value"
  ) %>% 
  group_by(item) %>% 
  ggdist::mean_hdi(.width = .95) %>% 
  arrange(factor(item, levels = tbl_orders)) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 3) %>% 
  flextable::line_spacing(space = 0.7) %>% 
  flextable::color(j = "value", color = "red") %>% 
  flextable::autofit()
```

# 参考

- <https://bookdown.org/content/4857/markov-chain-monte-carlo.html#easy-hmc-ulam-brm>
- <https://discourse.mc-stan.org/t/brm-syntax-for-guessing-probability-with-interaction-terms/16443/3>